apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::467121734390:role/eks-node-group-nodes
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::467121734390:role/AWSReservedSSO_AdministratorAccess_29dab7859ba5d4a8
      username: AWSReservedSSO_AdministratorAccess_29dab7859ba5d4a8
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
  creationTimestamp: "2023-04-28T19:02:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "178724"
  uid: 5f4096ac-de07-4ed0-b8cd-7e6587a829cd
