apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::467121734390:role/eks-node-group-nodes
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::467121734390:role/AWSReservedSSO_AdministratorAccess_29dab7859ba5d4a8
      username: AWSReservedSSO_AdministratorAccess_29dab7859ba5d4a8
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-29T18:18:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "856"
  uid: 632c9558-5d4a-4f06-a121-5283d5cfd278
